version: '2'
services:
  mysql:
    image: docker.tianlu56.com.cn/pro/disconf:mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'sklinux'
    volumes:
      - ./initsql:/docker-entrypoint-initdb.d
  redis:
    image: docker.tianlu56.com.cn/pro/redis
  zookeeper:
    image: docker.tianlu56.com.cn/pro/zookeeper
  disconf:
    image: docker.tianlu56.com.cn/pro/disconf/disconf
    volumes:
      - ./war:/disconf/war
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - zookeeper
  nginx:
    image: docker.tianlu56.com.cn/pro/nginx
    ports:
      - "9999:9999"
    volumes:
      - ./disconf/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./war/html:/html
    depends_on:
      - disconf
